export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
