export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SELECT_CATEGORY = "SELECT_CATEGORY";

export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const SELECT_TASK = "SELECT_TASK";

export const UPDATE_SETTINGS = "UPDATE_SETTINGS";

export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
